#PBS -N redox
#PBS -q gemini-gpu
#PBS -o log.$PBS_JOBID
#PBS -e error.$PBS_JOBID
#PBS -l nodes=1:ppn=1:gpus=1:exclusive_gpus
#PBS -l walltime=120:00:00

cd $PBS_O_WORKDIR

hostname

module load cuda/9.0
module load anaconda3/latest

# fill this in with your OpenMM conda environment
source activate my_python-3.6

export OPENMM_CUDA_COMPILER=$(which nvcc)
export CUDA_CACHE_PATH=${TMPDIR}
export OPENMM_CPU_THREADS=1

python run_openMM_1context.py npt_mc_3pctbq.pdb  md_2V.key > energy_2V_3pctSq_300bmibf4.log
